//  clientId = 1 (autogenerated),
//  accounts = [accountId, accountId],
//  name = test,
//  city = bcn,
//  contact_info = {
//      phone = 12345678,
//      email = email@email.com
//   }

class Client {
    constructor(accountId, name, city, contactInfo) {
        this.accounts = [accountId], 
        this.name = name, 
        this.city = city, 
        this.contactInfo = contactInfo, 
        this.clientId = Math.floor(Math.random() * 1000)
    }
}

module.exports = Client; 